#!/bin/bash
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Restoring the app directory..."
ynh_restore "$install_dir"
chown -R "$app:www-data" "$install_dir"

ynh_script_progression "Restoring the data directory..."
ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"

ynh_script_progression "Restoring system configurations..."
ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

mkdir -p "/var/log/$app"
touch "/var/log/$app/$app.log"
chown -R "$app:$app" "/var/log/$app"
ynh_restore "/etc/logrotate.d/$app"

yunohost service add "$app" --description="MoreLater content calendar" --log="/var/log/$app/$app.log"

ynh_script_progression "Starting $app..."
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Ready"
ynh_systemctl --service=nginx --action=reload

ynh_script_progression "Restoration of $app completed"
